[tools]
node = '24'
deno = '2.5.6'
bun = '1.3.3'
'npm:pnpm' = '10.24.0'
'npm:@anthropic-ai/claude-code' = '2.0.56'
'npm:@openai/codex' = '0.63.0'
python = '3.14.1'
uv = '0.9.15'
go = '1.25.5'
rust = '1.91.1'

[hooks]
# FIXME: corepack would be removed from Node.js https://socket.dev/blog/node-js-takes-steps-towards-removing-corepack
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true
# idiomatic version files would be disabled by default, so it is needed to enable explicitly
idiomatic_version_file_enable_tools = ["node"]
