[tools]
node = '24'
deno = '2.6.4'
bun = '1.3.5'
'npm:pnpm' = '10.27.0'
'npm:@anthropic-ai/claude-code' = '2.0.76'
'npm:@openai/codex' = '0.77.0'
python = '3.14.2'
uv = '0.9.21'
go = '1.25.5'
rust = '1.92.0'

[hooks]
# FIXME: corepack would be removed from Node.js https://socket.dev/blog/node-js-takes-steps-towards-removing-corepack
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true
# idiomatic version files would be disabled by default, so it is needed to enable explicitly
idiomatic_version_file_enable_tools = ["node"]
