[tools]
node = '24'
deno = '2.6.8'
bun = '1.3.8'
'npm:pnpm' = '10.28.2'
'npm:@anthropic-ai/claude-code' = '2.1.32'
'npm:@openai/codex' = '0.97.0'
python = '3.14.3'
uv = '0.9.30'
go = '1.25.7'
rust = '1.93.0'

[hooks]
# FIXME: corepack would be removed from Node.js https://socket.dev/blog/node-js-takes-steps-towards-removing-corepack
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true
# idiomatic version files would be disabled by default, so it is needed to enable explicitly
idiomatic_version_file_enable_tools = ["node"]
